name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o codigo
        uses: actions/checkout@v4.2.2
      
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SECRET_RACO1 }}
          password: ${{ secrets.SECRET_RACO }}
      
      - name: Construcao e envio da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            raco21/fake-shop-desafio:v${{ github.run_number }}
            raco21/fake-shop-desafio:latest
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:       
      - name: Obtendo o codigo
        uses: actions/checkout@v4.2.2

      - name: Set Kubernetes Context
        uses: Azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v5     
        with:
          manifests: |
            k8s/deployment.yaml
          images: raco21/fake-shop-desafio:v${{ github.run_number }}
          
