name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

  jobs:
    CI:
      runs-on: ubuntu-latest
      steps:
       - run: echo "obeter codigo"
       - run: echo "Executar o Docker build"
       - run: echo "Enviar a imaggem Docker para o Docker hub"

    CD:
      runs-on: ubuntu-latest
      steps:       
       - run: echo "obeter codigo"
       - run: echo "Executar o kubeconfig"
       - run: echo "Executar apply"
